name: homesite-compose

services:
  homesite:
    image: ${DOCKER_REGISTRY-}homesite
    container_name: homesite
    build:
      context: .
      dockerfile: HomeSite/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - HOST_SERVERS_PATH=${PWD}/hs_data/servers
    depends_on:
      - db
    user: root
    labels:
      - caddy=${DOMAIN_NAME}
      - caddy.reverse_proxy={{upstreams 8080}}
    networks:
      - hs_network
      - mc_network
    volumes:
      - ./hs_data/config:/app/Config
      - ./hs_data/config/config.json:/app/config/config.json
      - ./hs_data/userStorage:/app/Share
      - /var/run/docker.sock:/var/run/docker.sock
      - ./hs_data/servers:/app/servers
    ports: []
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"


  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - hs_network
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  mc_proxy:
    image: itzg/mc-router
    container_name: mc_proxy
    environment:
      - IN_DOCKER=true
    ports:
      - "25565:25565/tcp"
    networks:
      - mc_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  proxy:
    image: lucaslorentz/caddy-docker-proxy:latest
    container_name: proxy
    restart: always
    depends_on:
      - homesite
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=mc_network,hs_network
    networks:
      - mc_network
      - hs_network
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - caddy_config:/config
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - hs_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    depends_on:
      - cadvisor
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    networks:
      - hs_network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_ROOT_URL=https://${DOMAIN_NAME}/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    networks:
      - hs_network
    user: "472"
    volumes:
      - ./grafana_data:/var/lib/grafana
    labels:
      - "caddy=${DOMAIN_NAME}"
      - "caddy.redir=/grafana /grafana/ 308"
      - "caddy.handle=/grafana*"
      - "caddy.handle.reverse_proxy={{upstreams 3000}}"
    restart: unless-stopped
    depends_on:
      - prometheus
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

networks:
  mc_network:
    name: mc_network
    driver: bridge
  hs_network:
    name: hs_network
    driver: bridge

volumes:
  caddy_data:
  caddy_config: