name: homesite-compose

services:
  homesite:
    image: ${DOCKER_REGISTRY-}homesite
    container_name: homesite
    build:
      context: .
      dockerfile: HomeSite/Dockerfile
    restart: always
    depends_on:
      - db
      - proxy
    user: root
    volumes:
      - ./config.json:/app/Config/config.json
      - ./hs_data/UserStorage:/app/Share
      - /var/run/docker.sock:/var/run/docker.sock
      - ./hs_data/servers:/app/servers
    ports: []


  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - hs_pg_data:/var/lib/postgresql/data
    restart: always

  proxy:
    image: caddy:2.11
    container_name: proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config


volumes:
  hs_pg_data:
  caddy_data:
  caddy_config:
