// <auto-generated />
using HomeSite.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeSite.Migrations.SharedRightsMigrations
{
    [DbContext(typeof(SharedRightsDBContext))]
    [Migration("20260220205819_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeSite.Entities.SharedRights", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<string>("ServerId")
                        .HasColumnType("text")
                        .HasColumnName("serverid");

                    b.Property<bool>("AddShareds")
                        .HasColumnType("boolean")
                        .HasColumnName("addshareds");

                    b.Property<bool>("EditMods")
                        .HasColumnType("boolean")
                        .HasColumnName("editmods");

                    b.Property<bool>("EditServerPreferences")
                        .HasColumnType("boolean")
                        .HasColumnName("editserverpreferences");

                    b.Property<bool>("SeeServerFiles")
                        .HasColumnType("boolean")
                        .HasColumnName("seeserverfiles");

                    b.Property<bool>("SendCommands")
                        .HasColumnType("boolean")
                        .HasColumnName("sendcommands");

                    b.Property<bool>("StartStopServer")
                        .HasColumnType("boolean")
                        .HasColumnName("startstopserver");

                    b.Property<bool>("UploadServer")
                        .HasColumnType("boolean")
                        .HasColumnName("uploadmods");

                    b.HasKey("UserId", "ServerId");

                    b.ToTable("shared");
                });
#pragma warning restore 612, 618
        }
    }
}
