// <auto-generated />
using HomeSite.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeSite.Migrations.ServerMigrations
{
    [DbContext(typeof(ServerDBContext))]
    [Migration("20260222223740_NewDomainName")]
    partial class NewDomainName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeSite.Entities.Server", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("description");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domainname");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.Property<int>("PublicPort")
                        .HasColumnType("integer")
                        .HasColumnName("publicport");

                    b.Property<int>("RCONPort")
                        .HasColumnType("integer")
                        .HasColumnName("rconport");

                    b.Property<string>("ServerCore")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("core");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("servers");
                });
#pragma warning restore 612, 618
        }
    }
}
